// --- VISUALIZATION TOOLS ---
// This script provides a suite of functions for visualizing hypothesis data generated by an automated analysis system.
// It includes capabilities for:
// - Calculating a weighted fitness score for each hypothesis.
// - Rendering an interactive hierarchical tree of hypotheses using D3.js.
// - Displaying aggregated hypothesis data in sunburst charts using Plotly.js.
// - Generating and managing interactive data tables for detailed hypothesis review.
// - Preparing data for dimensionality reduction techniques like t-SNE.
// - Rendering a t-SNE-based visualization of hypotheses.
// - Rendering a co-occurrence heatmap of attributes from top hypotheses.
// - Rendering a scatterplot for metric analysis.

/**
 * @property {object} currentSortState - Global state object to track the current sorting configuration for the hypothesis tables.
 * @property {string} currentSortState.key - The data key to sort by (e.g., 'Fitness_Score').
 * @property {string} currentSortState.direction - The sort direction ('asc' or 'desc').
 */
let currentSortState = {
    key: 'Fitness_Score',
    direction: 'desc'
};

/**
 * @const {Array<object>} tableHeaders - Defines the structure and properties of the hypothesis table columns.
 * This ensures a consistent column order and specifies which columns are sortable.
 */
const tableHeaders = [
    { key: 'Select', label: 'Select', sortable: false },
    { key: 'Hypothesis_Text', label: 'Hypothesis', sortable: false },
    { key: 'Fitness_Score', label: 'Score', sortable: true },
    { key: 'Significance_qValue', label: 'q-Value', sortable: true },
    { key: 'Impact_Lift', label: 'Impact', sortable: true },
    { key: 'Coverage', label: 'Coverage', sortable: true },
    { key: 'Diversity', label: 'Diversity', sortable: true },
    { key: 'Homogeneity', label: 'Homogeneity', sortable: true },
    { key: 'source_method', label: 'Method', sortable: true }
];

/**
 * Numeric formatting helpers
 */
function isValidNumber(value) {
    return value !== null && value !== undefined && value !== '' && !isNaN(Number(value));
}

function formatMetricValue(value, options = {}) {
    const {
        normalDecimals = 5,
        sciDecimals = 2,
        tinyThreshold = 1e-4,
        fallback = 'N/A'
    } = options;

    if (!isValidNumber(value)) return fallback;

    const num = Number(value);

    if (!Number.isFinite(num)) {
        if (num === Infinity) return '∞';
        if (num === -Infinity) return '-∞';
        return fallback;
    }

    if (num === 0) return '0';

    if (Math.abs(num) < tinyThreshold) {
        return num.toExponential(sciDecimals);
    }

    return num.toFixed(normalDecimals).replace(/\.?0+$/, '');
}

function formatScore(value) {
    return formatMetricValue(value, { normalDecimals: 4, sciDecimals: 2, fallback: '0' });
}

function formatQValue(hyp) {
    if (hyp?.Significance_qValue_Formatted !== undefined && hyp?.Significance_qValue_Formatted !== null && hyp?.Significance_qValue_Formatted !== '') {
        return hyp.Significance_qValue_Formatted;
    }
    return formatMetricValue(hyp?.Significance_qValue, {
        normalDecimals: 6,
        sciDecimals: 2,
        fallback: 'N/A'
    });
}

function formatHomogeneity(hyp) {
    if (hyp?.Homogeneity_Formatted !== undefined && hyp?.Homogeneity_Formatted !== null && hyp?.Homogeneity_Formatted !== '') {
        return hyp.Homogeneity_Formatted;
    }
    return formatMetricValue(hyp?.Homogeneity, {
        normalDecimals: 6,
        sciDecimals: 2,
        fallback: 'N/A'
    });
}

function formatImpact(value) {
    if (!isValidNumber(value)) return 'N/A';
    return `${Number(value).toFixed(2)}x`;
}

function formatCoverage(value) {
    if (!isValidNumber(value)) return 'N/A';
    return `${(Number(value) * 100).toFixed(1)}%`;
}

function formatDiversity(value) {
    return formatMetricValue(value, {
        normalDecimals: 4,
        sciDecimals: 2,
        fallback: 'N/A'
    });
}

/**
 * Calculates a composite fitness score for each hypothesis based on a weighted average of its normalized metrics.
 * The function normalizes several metrics to a 0-1 scale, transforms the q-value for proper weighting,
 * and then computes the final score.
 * @param {Array<object>} hypotheses - The array of hypothesis objects to be scored.
 * @returns {Array<object>} A new array of hypothesis objects, each augmented with a Fitness_Score, sorted in descending order by that score.
 */
function calculateAndSortByFitnessScore(hypotheses) {
    if (!hypotheses || hypotheses.length === 0) {
        return [];
    }

    // Create a deep copy to avoid mutating the original data.
    let df = JSON.parse(JSON.stringify(hypotheses));

    // Define the weights for each metric in the fitness score calculation.
    const weights = {
        Significance_qValue: 0.25,
        Impact_Lift: 0.25,
        Coverage: 0.25,
        Diversity: 0.25,
        Homogeneity: 0.25
    };

    // --- Metric Normalization ---
    const metrics_to_normalize = ['Impact_Lift', 'Coverage', 'Homogeneity', 'Diversity'];
    metrics_to_normalize.forEach(metric => {
        if (df.every(h => h[metric] !== undefined)) {
            const validValues = df
                .map(h => Number(h[metric]))
                .filter(v => Number.isFinite(v));

            if (validValues.length === 0) return;

            const mean = validValues.reduce((a, b) => a + b, 0) / validValues.length;

            df.forEach(h => {
                const numericValue = Number(h[metric]);
                if (!Number.isFinite(numericValue)) {
                    h[metric] = mean;
                } else {
                    h[metric] = numericValue;
                }
            });

            const minVal = Math.min(...df.map(h => h[metric]));
            const maxVal = Math.max(...df.map(h => h[metric]));
            const range = maxVal - minVal;

            df.forEach(h => {
                h[`${metric}_norm`] = range > 0 ? (h[metric] - minVal) / range : 0.5;
            });
        }
    });

    // --- q-Value Transformation and Normalization ---
    if (df.every(h => h.Significance_qValue !== undefined)) {
        const epsilon = 1e-10;
        df.forEach(h => {
            const q = Number(h.Significance_qValue);
            const safeQ = Number.isFinite(q) ? Math.min(Math.max(q, 0), 1) : 1;
            h.qValue_transformed = -Math.log10(safeQ + epsilon);
        });

        const minQ = Math.min(...df.map(h => h.qValue_transformed));
        const maxQ = Math.max(...df.map(h => h.qValue_transformed));
        const rangeQ = maxQ - minQ;

        df.forEach(h => {
            h.Significance_qValue_norm = rangeQ > 0 ? (h.qValue_transformed - minQ) / rangeQ : 0.5;
        });
    }

    // --- Final Score Calculation ---
    df.forEach(h => {
        h.Fitness_Score = 0.0;
        for (const [metric, weight] of Object.entries(weights)) {
            const norm_col = `${metric}_norm`;
            if (h[norm_col] !== undefined && !isNaN(h[norm_col])) {
                h.Fitness_Score += h[norm_col] * weight;
            }
        }
    });

    return df.sort((a, b) => b.Fitness_Score - a.Fitness_Score);
}

/**
 * Prepares hypothesis data for t-SNE by performing one-hot encoding on its categorical attributes,
 * running the t-SNE algorithm, and appending the 2D coordinates to the data.
 * @param {Array<object>} hypotheses - The array of scored and sorted hypothesis objects.
 * @returns {Array<object>} A new array of objects with t-SNE coordinates, suitable for plotting.
 */
function prepareDataForTSNE(hypotheses) {
    if (!hypotheses || hypotheses.length === 0) {
        console.log("No hypotheses data to prepare for t-SNE.");
        return [];
    }

    const allAttributeValuePairs = new Set();
    hypotheses.forEach(hyp => {
        const attributes = extractAttributesFromHypothesis(hyp.Hypothesis_Text);
        attributes.forEach(attr => {
            allAttributeValuePairs.add(`${attr.attribute} = '${attr.value}'`);
        });
    });
    const featureColumns = Array.from(allAttributeValuePairs);

    const encodedData = hypotheses.map(hyp => {
        const row = {
            'Hypothesis': hyp.Hypothesis_Text,
            'Score': hyp.Fitness_Score,
            'q-Value': hyp.Significance_qValue,
            'Impact': hyp.Impact_Lift,
            'Coverage': hyp.Coverage,
            'Diversity': hyp.Diversity,
            'Homogeneity': hyp.Homogeneity,
        };
        featureColumns.forEach(col => row[col] = 0);
        const currentAttributes = extractAttributesFromHypothesis(hyp.Hypothesis_Text);
        currentAttributes.forEach(attr => {
            const pairString = `${attr.attribute} = '${attr.value}'`;
            if (row.hasOwnProperty(pairString)) {
                row[pairString] = 1;
            }
        });
        return row;
    });

    const tsneInput = encodedData.map(row => {
        const numericRow = { ...row };
        delete numericRow.Hypothesis;
        return Object.values(numericRow);
    });
    console.log(`t-SNE input created with ${tsneInput.length} rows and ${tsneInput[0] ? tsneInput[0].length : 0} columns.`);

    var tsne = new tsnejs.tSNE({
        dim: 2,
        perplexity: 30.0,
        epsilon: 10
    });
    tsne.initDataRaw(tsneInput);

    for (var k = 0; k < 500; k++) {
        tsne.step();
    }

    var Y = tsne.getSolution();
    console.log("t-SNE solution generated. Dimensions:", Y.length, "x", Y[0] ? Y[0].length : 0);
    if (Y.length > 0) console.log("First t-SNE coordinate pair:", Y[0]);

    encodedData.forEach((row, i) => {
        if (Y[i]) {
            row.tsneX = Y[i][0];
            row.tsneY = Y[i][1];
        }
    });
    if (encodedData.length > 0) console.log("First row of data after adding t-SNE coordinates:", encodedData[0]);

    console.log("--- Data with t-SNE Coordinates (First 10 Rows) ---");
    console.table(encodedData.slice(0, 10));

    return encodedData;
}


// --- D3 HIERARCHICAL TREE VISUALIZATION ---

class TreeNode {
    constructor(name, operator, qValue, impact, coverage, diversity, homogeneity, hypothesisText, level = 0, fitnessScore = null) {
        this.name = name;
        this.operator = operator;
        this.qValue = qValue;
        this.impact = impact;
        this.coverage = coverage;
        this.diversity = diversity;
        this.homogeneity = homogeneity;
        this.hypothesisText = hypothesisText;
        this.level = level;
        this.fitnessScore = fitnessScore;
        this.children = [];
        this.parent = null;
    }

    addChild(child) {
        child.parent = this;
        this.children.push(child);
        return this;
    }
}

function extractAttributesFromHypothesis(hypothesisText) {
    if (typeof hypothesisText !== 'string') return [];
    const attributes = [];
    const regex = /`(\w+(?:_\w+)*)`\s+(?:is|=)\s+['"]([^'"]+)['"]/g;
    let match;

    while ((match = regex.exec(hypothesisText)) !== null) {
        attributes.push({
            attribute: match[1],
            value: match[2]
        });
    }

    return attributes;
}

function buildHypothesesTree(hypotheses) {
    const root = new TreeNode("Dataset Root", null, null, null, null, null, null, "Root of all hypotheses", 0);

    const operatorGroups = {
        'greater than': [],
        'less than': [],
        'variance is higher': []
    };
    hypotheses.forEach(hyp => {
        if (hyp && hyp.Operator && operatorGroups[hyp.Operator]) {
            operatorGroups[hyp.Operator].push(hyp);
        }
    });

    Object.keys(operatorGroups).forEach(operator => {
        if (operatorGroups[operator].length === 0) return;

        const operatorTitle = operator === 'greater than' ? 'Mean > Global' :
                              operator === 'less than' ? 'Mean < Global' :
                              'Variance > Global';

        const operatorNode = new TreeNode(
            operatorTitle, operator, null, null, null, null, null,
            `Hypotheses with ${operator} comparison`, 1
        );

        operatorGroups[operator].forEach((hyp) => {
            const attributes = extractAttributesFromHypothesis(hyp.Hypothesis_Text);
            if (attributes.length === 0) {
                console.warn(`Could not extract attributes from hypothesis: "${hyp.Hypothesis_Text}"`);
                return;
            }

            let currentNode = operatorNode;

            attributes.forEach((attr, attrIndex) => {
                const nodeName = `${attr.attribute} = '${attr.value}'`;
                let childNode = currentNode.children.find(child => child.name === nodeName);

                if (!childNode) {
                    childNode = new TreeNode(
                        nodeName, operator, null, null, null, null, null,
                        `Subgroup for ${nodeName}`, 2 + attrIndex
                    );
                    currentNode.addChild(childNode);
                }

                if (attrIndex === attributes.length - 1) {
                    childNode.qValue = hyp.Significance_qValue;
                    childNode.impact = hyp.Impact_Lift;
                    childNode.coverage = hyp.Coverage;
                    childNode.diversity = hyp.Diversity;
                    childNode.homogeneity = hyp.Homogeneity;
                    childNode.hypothesisText = hyp.Hypothesis_Text;
                    childNode.fitnessScore = hyp.Fitness_Score;
                }

                currentNode = childNode;
            });
        });

        if (operatorNode.children.length > 0) {
            root.addChild(operatorNode);
        }
    });

    return root;
}

function renderHypothesisTree(hypotheses) {
    const container = document.getElementById('tree-container');
    if (!container) {
        console.error("Tree container element not found.");
        return;
    }
    container.innerHTML = '';

    if (!hypotheses || hypotheses.length === 0) {
        container.innerHTML = '<div class="info-message">No hypotheses provided to build the tree.</div>';
        return;
    }

    const validHypotheses = hypotheses.filter(h => h && h.Operator && h.Hypothesis_Text);
    if (validHypotheses.length === 0) {
        container.innerHTML = '<div class="error-message">Hypothesis data is incomplete and cannot be rendered.</div>';
        return;
    }

    const hypothesesTree = buildHypothesesTree(validHypotheses);
    if (!hypothesesTree.children || hypothesesTree.children.length === 0) {
        container.innerHTML = '<div class="error-message">Could not build the hierarchical structure from the provided data.</div>';
        return;
    }

    drawD3Tree(hypothesesTree, container);
}

function drawD3Tree(rootData, container) {
    const margin = { top: 20, right: 120, bottom: 20, left: 180 };
    const width = 1400 - margin.right - margin.left;
    const height = 1000 - margin.top - margin.bottom;
    let i = 0;
    const duration = 750;

    let tooltip = d3.select("#tooltip");
    if (tooltip.empty()) {
        tooltip = d3.select("body").append("div")
            .attr("class", "tooltip")
            .attr("id", "tooltip")
            .style("position", "absolute")
            .style("opacity", 0)
            .style("pointer-events", "none")
            .style("background", "rgba(0,0,0,0.8)")
            .style("color", "white")
            .style("padding", "10px")
            .style("border-radius", "4px")
            .style("font-family", "sans-serif")
            .style("font-size", "12px");
    }

    d3.select(container).selectAll("*").remove();
    const svg = d3.select(container)
        .append("svg")
        .attr("width", width + margin.right + margin.left)
        .attr("height", height + margin.top + margin.bottom)
        .attr("class", "tree-svg");
    const g = svg.append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);

    const tree = d3.tree().size([height, width]);
    const root = d3.hierarchy(rootData, d => d.children);
    root.x0 = height / 2;
    root.y0 = 0;

    root.children.forEach(collapse);
    update(root);

    function collapse(d) {
        if (d.children) {
            d._children = d.children;
            d._children.forEach(collapse);
            d.children = null;
        }
    }

    function update(source) {
        const treeData = tree(root);
        const nodes = treeData.descendants();
        const links = treeData.descendants().slice(1);

        nodes.forEach(d => { d.y = d.depth * 180; });

        const node = g.selectAll('g.node')
            .data(nodes, d => d.id || (d.id = ++i));

        const nodeEnter = node.enter().append('g')
            .attr('class', 'node')
            .attr("transform", d => `translate(${source.y0},${source.x0})`)
            .on('click', click);

        nodeEnter.append('circle')
            .attr('class', 'node')
            .attr('r', 1e-6)
            .style("stroke", "#667eea")
            .style("stroke-width", "2px")
            .on("mouseover", function(event, d) {
                tooltip.transition().duration(200).style("opacity", .9);
                let tooltipContent = `<strong>${d.data.name}</strong>`;
                if (d.data.qValue !== null && d.data.qValue !== undefined) {
                    tooltipContent += `<br/>
                                <strong>Score:</strong> ${formatScore(d.data.fitnessScore)}<br/>
                                <strong>q-Value:</strong> ${formatMetricValue(d.data.qValue, { normalDecimals: 6, sciDecimals: 2 })}<br/>
                                <strong>Impact:</strong> ${formatImpact(d.data.impact)}<br/>
                                <strong>Coverage:</strong> ${formatCoverage(d.data.coverage)}<br/>
                                <strong>Homogeneity:</strong> ${formatMetricValue(d.data.homogeneity, { normalDecimals: 6, sciDecimals: 2 })}<br/>
                                <hr style="margin: 4px 0;">
                                <small>${d.data.hypothesisText || 'Intermediate Node'}</small>`;
                } else {
                    tooltipContent += `<br/><small>${d.data.hypothesisText}</small>`;
                }
                tooltip.html(tooltipContent)
                    .style("left", (event.pageX + 15) + "px")
                    .style("top", (event.pageY - 28) + "px");
            })
            .on("mouseout", function() {
                tooltip.transition().duration(500).style("opacity", 0);
            });

        nodeEnter.append('text')
            .attr("dy", ".35em")
            .attr("x", d => d.children || d._children ? -13 : 13)
            .attr("text-anchor", d => d.children || d._children ? "end" : "start")
            .text(d => d.data.name);

        const nodeUpdate = nodeEnter.merge(node);
        nodeUpdate.transition()
            .duration(duration)
            .attr("transform", d => `translate(${d.y},${d.x})`);

        nodeUpdate.select('circle.node')
            .attr('r', 8)
            .style("fill", d => d._children ? "#667eea" : (d.data.qValue !== null && d.data.qValue !== undefined) ? "#28a745" : "#fff")
            .attr('cursor', 'pointer');

        const nodeExit = node.exit().transition()
            .duration(duration)
            .attr("transform", d => `translate(${source.y},${source.x})`)
            .remove();

        nodeExit.select('circle').attr('r', 1e-6);
        nodeExit.select('text').style('fill-opacity', 1e-6);

        const link = g.selectAll('path.link')
            .data(links, d => d.id);

        const linkEnter = link.enter().insert('path', "g")
            .attr("class", "link")
            .style("fill", "none")
            .style("stroke", "#ccc")
            .style("stroke-width", "2px")
            .attr('d', d => {
                const o = { x: source.x0, y: source.y0 };
                return `M${o.y},${o.x}C${(o.y + o.y) / 2},${o.x} ${(o.y + o.y) / 2},${o.x} ${o.y},${o.x}`;
            });

        const linkUpdate = linkEnter.merge(link);
        linkUpdate.transition()
            .duration(duration)
            .attr('d', d => `M${d.y},${d.x}C${(d.y + d.parent.y) / 2},${d.x} ${(d.y + d.parent.y) / 2},${d.parent.x} ${d.parent.y},${d.parent.x}`);

        link.exit().transition()
            .duration(duration)
            .attr('d', d => {
                const o = { x: source.x, y: source.y };
                return `M${o.y},${o.x}C${(o.y + o.y) / 2},${o.x} ${(o.y + o.y) / 2},${o.x} ${o.y},${o.x}`;
            })
            .remove();

        nodes.forEach(d => {
            d.x0 = d.x;
            d.y0 = d.y;
        });

        function click(event, d) {
            if (d.children) {
                d._children = d.children;
                d.children = null;
            } else {
                d.children = d._children;
                d._children = null;
            }
            update(d);
        }
    }
}

function buildSunburstData(hypotheses) {
    const sunburst = {
        ids: ['Root'],
        labels: [targetInfo.name],
        parents: [''],
        values: [0],
        scores: [0],
        counts: [0]
    };

    const operatorMap = {
        'greater than': `Mean > ${targetInfo.mean.toFixed(2)}`,
        'less than': `Mean < ${targetInfo.mean.toFixed(2)}`,
        'variance is higher': `Variance > ${targetInfo.variance.toFixed(2)}`
    };

    Object.values(operatorMap).forEach(opLabel => {
        if (!sunburst.ids.includes(opLabel)) {
            sunburst.ids.push(opLabel);
            sunburst.labels.push(opLabel);
            sunburst.parents.push('Root');
            sunburst.values.push(0);
            sunburst.scores.push(0);
            sunburst.counts.push(0);
        }
    });

    hypotheses.forEach(hyp => {
        const attributes = extractAttributesFromHypothesis(hyp.Hypothesis_Text);
        let currentParent = operatorMap[hyp.Operator];
        if (!currentParent) return;

        const pathIds = ['Root', currentParent];

        attributes.forEach((attr) => {
            const nodeLabel = `${attr.attribute} = '${attr.value}'`;
            const pathId = `${pathIds[pathIds.length - 1]}-${nodeLabel}`;

            if (!sunburst.ids.includes(pathId)) {
                sunburst.ids.push(pathId);
                sunburst.labels.push(nodeLabel);
                sunburst.parents.push(currentParent);
                sunburst.values.push(0);
                sunburst.scores.push(0);
                sunburst.counts.push(0);
            }
            currentParent = pathId;
            pathIds.push(currentParent);
        });

        const leafValue = (hyp.Coverage || 0) * 100;
        const leafScore = hyp.Fitness_Score || 0;

        pathIds.forEach(idInPath => {
            const index = sunburst.ids.indexOf(idInPath);
            if (index !== -1) {
                sunburst.values[index] += leafValue;
                sunburst.scores[index] += leafScore;
                sunburst.counts[index] += 1;
            }
        });
    });

    sunburst.customdata = sunburst.scores.map((score, i) => {
        const count = sunburst.counts[i];
        return count > 0 ? formatScore(score / count) : "N/A";
    });

    return sunburst;
}

function renderSunburstCharts(hypotheses) {
    const container = document.getElementById('sunburst-plot-container');
    if (!container) {
        console.error("Sunburst container element not found.");
        return;
    }

    container.className = '';
    container.style = '';

    container.innerHTML = `
        <div class="p-4 border rounded-lg bg-white flex flex-col items-center" style="height: 700px; overflow: auto;">
            <h4 class="text-md font-semibold text-gray-800 mb-2">Top 10 Hypotheses by Category (by Score)</h4>
            <div id="sunburst-top10" style="height: 600px; width: 600px;"></div>
            <hr class="my-8 w-4/5">
            <h4 class="text-md font-semibold text-gray-800 mb-2">All Hypotheses</h4>
            <div id="sunburst-all" style="height: 600px; width: 600px;"></div>
        </div>
    `;

    const top10Hypotheses = [
        ...categorizedHypotheses['greater than'].slice(0, 10),
        ...categorizedHypotheses['less than'].slice(0, 10),
        ...categorizedHypotheses['variance is higher'].slice(0, 10)
    ];

    const allData = buildSunburstData(hypotheses);
    const top10Data = buildSunburstData(top10Hypotheses);

    const layout = {
        width: 600,
        height: 600,
        margin: { l: 0, r: 0, b: 0, t: 20 },
    };

    const hovertemplate = '<b>%{label}</b><br>Average Score: %{customdata}<extra></extra>';

    if (typeof Plotly !== 'undefined') {
        Plotly.newPlot('sunburst-all', [{
            type: "sunburst",
            ids: allData.ids,
            labels: allData.labels,
            parents: allData.parents,
            values: allData.values,
            customdata: allData.customdata,
            hovertemplate: hovertemplate,
            leaf: { opacity: 0.6 },
            marker: { line: { width: 1.5 } },
            branchvalues: 'total'
        }], layout);

        Plotly.newPlot('sunburst-top10', [{
            type: "sunburst",
            ids: top10Data.ids,
            labels: top10Data.labels,
            parents: top10Data.parents,
            values: top10Data.values,
            customdata: top10Data.customdata,
            hovertemplate: hovertemplate,
            leaf: { opacity: 0.6 },
            marker: { line: { width: 1.5 } },
            branchvalues: 'total'
        }], layout);
    } else {
        console.error("Plotly.js library not found.");
        document.getElementById('sunburst-all').innerHTML = '<div class="error-message">Plotly.js library not found.</div>';
        document.getElementById('sunburst-top10').innerHTML = '<div class="error-message">Plotly.js library not found.</div>';
    }
}

/**
 * Renders sortable and expandable tables for each category of hypotheses.
 * This function preserves the scroll position and checkbox states across re-renders.
 */
function drawHypothesisTables() {
    const container = document.getElementById('hypothesis-tables-container');
    if (!container) return;

    const scrollableDiv = container.querySelector('div[style*="overflow-y: auto"]');
    const scrollPosition = scrollableDiv ? scrollableDiv.scrollTop : 0;

    const checkedHypotheses = new Set();
    document.querySelectorAll('.hypothesis-checkbox:checked').forEach(checkbox => {
        checkedHypotheses.add(checkbox.dataset.hypothesisText);
    });

    let finalHTML = '';

    const categories = [
        { id: 'greater than', title: 'Hypotheses: Mean Greater than Global Mean' },
        { id: 'less than', title: 'Hypotheses: Mean Less than Global Mean' },
        { id: 'variance is higher', title: 'Hypotheses: Variance is Higher' }
    ];

    const sortedCategorizedHypotheses = {};
    for (const catId in categorizedHypotheses) {
        sortedCategorizedHypotheses[catId] = [...categorizedHypotheses[catId]].sort((a, b) => {
            const key = currentSortState.key;
            const direction = currentSortState.direction === 'asc' ? 1 : -1;

            let valA = a[key];
            let valB = b[key];

            if (typeof valA === 'string' && typeof valB === 'string') {
                return valA.localeCompare(valB) * direction;
            }

            valA = Number(valA);
            valB = Number(valB);

            if (!Number.isFinite(valA)) valA = currentSortState.direction === 'asc' ? Infinity : -Infinity;
            if (!Number.isFinite(valB)) valB = currentSortState.direction === 'asc' ? Infinity : -Infinity;

            return (valA - valB) * direction;
        });
    }

    categories.forEach(cat => {
        const hypothesesForCategory = sortedCategorizedHypotheses[cat.id];
        if (hypothesesForCategory && hypothesesForCategory.length > 0) {
            const totalCount = hypothesesForCategory.length;
            finalHTML += `<h4 class="text-md font-semibold text-gray-800 mt-4 mb-2">${cat.title} (${totalCount} hypotheses found)</h4>`;

            let headerHTML = '<tr>';
            tableHeaders.forEach(header => {
                if (header.sortable) {
                    let iconClass = 'fa-sort';
                    if (currentSortState.key === header.key) {
                        iconClass = currentSortState.direction === 'asc' ? 'fa-sort-up' : 'fa-sort-down';
                    }
                    headerHTML += `<th class="px-4 py-2 border-b text-left text-xs font-semibold text-gray-600 uppercase sortable-header cursor-pointer" data-sort-key="${header.key}">
                                        <div class="flex items-center">
                                            <span>${header.label}</span>
                                            <i class="fas ${iconClass} ml-2"></i>
                                        </div>
                                    </th>`;
                } else {
                    headerHTML += `<th class="px-4 py-2 border-b text-left text-xs font-semibold text-gray-600 uppercase">${header.label}</th>`;
                }
            });
            headerHTML += '</tr>';

            finalHTML += `<div class="overflow-x-auto">
                                <table class="min-w-full bg-white border">
                                    <thead class="bg-gray-100">${headerHTML}</thead>
                                    <tbody>`;

            hypothesesForCategory.forEach(hyp => {
                const sanitizedHypText = String(hyp.Hypothesis_Text || '').replace(/"/g, '&quot;');
                const isChecked = checkedHypotheses.has(sanitizedHypText) ? 'checked' : '';

                finalHTML += `
                    <tr class="hover:bg-gray-50 text-sm">
                        <td class="px-4 py-2 border-b text-center">
                            <input type="checkbox" class="hypothesis-checkbox h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" 
                                   data-hypothesis-text="${sanitizedHypText}"
                                   data-q-value="${hyp.Significance_qValue ?? ''}"
                                   data-q-value-formatted="${formatQValue(hyp)}"
                                   data-impact-lift="${hyp.Impact_Lift ?? ''}"
                                   data-coverage="${hyp.Coverage ?? ''}"
                                   data-homogeneity="${hyp.Homogeneity ?? ''}"
                                   data-homogeneity-formatted="${formatHomogeneity(hyp)}"
                                   data-fitness-score="${hyp.Fitness_Score ?? ''}"
                                   data-source-method="${hyp.source_method ?? ''}"
                                   ${isChecked}>
                        </td>
                        <td class="px-4 py-2 border-b">${String(hyp.Hypothesis_Text || '').replace(/\*\*|`/g, '')}</td>
                        <td class="px-4 py-2 border-b font-bold">${formatScore(hyp.Fitness_Score || 0)}</td>
                        <td class="px-4 py-2 border-b">${formatQValue(hyp)}</td>
                        <td class="px-4 py-2 border-b">${formatImpact(hyp.Impact_Lift)}</td>
                        <td class="px-4 py-2 border-b">${formatCoverage(hyp.Coverage)}</td>
                        <td class="px-4 py-2 border-b">${formatDiversity(hyp.Diversity)}</td>
                        <td class="px-4 py-2 border-b">${formatHomogeneity(hyp)}</td>
                        <td class="px-4 py-2 border-b">${hyp.source_method ?? 'N/A'}</td>
                    </tr>`;
            });

            finalHTML += `</tbody></table></div>`;
        }
    });

    if (finalHTML === '') {
        finalHTML = `<div class="text-center text-gray-500 p-8">No significant hypotheses were found.</div>`;
    }

    container.innerHTML = `<div style="max-height: 600px; overflow-y: auto; padding-right: 15px;">${finalHTML}</div>`;
    const newScrollableDiv = container.querySelector('div[style*="overflow-y: auto"]');
    if (newScrollableDiv) {
        newScrollableDiv.scrollTop = scrollPosition;
    }

    document.querySelectorAll('.sortable-header').forEach(header => {
        header.addEventListener('click', () => {
            const sortKey = header.dataset.sortKey;
            if (currentSortState.key === sortKey) {
                currentSortState.direction = currentSortState.direction === 'asc' ? 'desc' : 'asc';
            } else {
                currentSortState.key = sortKey;
                currentSortState.direction = 'desc';
            }
            drawHypothesisTables();
        });
    });
}

function renderTSNE(hypotheses) {
    const container = document.getElementById('hypotheses-cloud-container');
    if (!container) {
        console.error("Hypotheses Cloud container element not found.");
        return;
    }

    const tsneData = prepareDataForTSNE(hypotheses);

    const validData = tsneData.filter(d =>
        d.tsneX != null && !isNaN(d.tsneX) &&
        d.tsneY != null && !isNaN(d.tsneY) &&
        d.Coverage != null && !isNaN(d.Coverage) &&
        d.Score != null && !isNaN(d.Score)
    );

    if (validData.length === 0) {
        container.innerHTML = `<div class="p-4 border rounded-lg bg-gray-50 flex items-center justify-center" style="height: 700px;"><p class="text-gray-500">No valid data available to render the t-SNE plot.</p></div>`;
        return;
    }

    container.innerHTML = `<div class="p-4 border rounded-lg bg-white flex justify-center" style="height: 900px; overflow: auto;"><div class="flex-shrink-0"><h4 class="text-md font-semibold text-gray-800 mb-2">Hypotheses Cloud (t-SNE Visualization)</h4><div id="tsne-plot-area" class="relative"></div></div></div>`;
    const plotArea = document.getElementById('tsne-plot-area');

    const margin = { top: 20, right: 120, bottom: 40, left: 50 };
    let width = 1100;
    let height = 700;

    let tooltip = d3.select("#tooltip");
    if (tooltip.empty()) {
        tooltip = d3.select("body").append("div")
            .attr("class", "tooltip")
            .attr("id", "tooltip")
            .style("position", "absolute")
            .style("opacity", 0)
            .style("pointer-events", "none")
            .style("background", "rgba(0,0,0,0.8)")
            .style("color", "white")
            .style("padding", "10px")
            .style("border-radius", "4px")
            .style("font-family", "sans-serif")
            .style("font-size", "12px")
            .style("z-index", "10");
    }

    const xScale = d3.scaleLinear().domain(d3.extent(validData, d => d.tsneX)).range([0, width]).nice();
    const yScale = d3.scaleLinear().domain(d3.extent(validData, d => d.tsneY)).range([height, 0]).nice();
    const radiusScale = d3.scaleSqrt().domain([0, d3.max(validData, d => d.Coverage)]).range([3, 25]);
    const colorScale = d3.scaleSequential(d3.interpolateViridis).domain(d3.extent(validData, d => d.Score));

    const xAxis = d3.axisBottom(xScale).ticks(10);
    const yAxis = d3.axisLeft(yScale).ticks(10);

    const svg = d3.select("#tsne-plot-area").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom);

    const g = svg.append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);
        
    const xAxisGroup = g.append("g")
        .attr("class", "x-axis")
        .attr("transform", `translate(0,${height})`)
        .call(xAxis);
    
    const yAxisGroup = g.append("g")
        .attr("class", "y-axis")
        .call(yAxis);

    xAxisGroup.append("text").attr("class", "axis-label").attr("x", width / 2).attr("y", margin.bottom - 10).attr("fill", "#000").style("text-anchor", "middle").text("t-SNE Dimension 1");
    yAxisGroup.append("text").attr("class", "axis-label").attr("transform", "rotate(-90)").attr("x", -height / 2).attr("y", -margin.left + 15).attr("fill", "#000").style("text-anchor", "middle").text("t-SNE Dimension 2");

    const clip = g.append("defs").append("clipPath")
        .attr("id", "clip-tsne")
        .append("rect")
        .attr("width", width)
        .attr("height", height);

    const circlesGroup = g.append("g")
        .attr("clip-path", "url(#clip-tsne)");

    circlesGroup.selectAll("circle")
        .data(validData)
        .enter()
        .append("circle")
        .attr("cx", d => xScale(d.tsneX))
        .attr("cy", d => yScale(d.tsneY))
        .attr("r", d => radiusScale(d.Coverage))
        .style("fill", d => colorScale(d.Score))
        .style("fill-opacity", 0.7)
        .style("stroke", "#fff")
        .style("stroke-width", 0.5)
        .on("mouseover", function(event, d) {
            tooltip.transition().duration(200).style("opacity", .95);
            tooltip.html(`<div style="max-width: 300px; word-wrap: break-word;"><strong>Hypothesis:</strong> ${d.Hypothesis.replace(/\*\*|`/g, '')}<br/><hr style="margin: 4px 0;"><strong>Score:</strong> ${formatScore(d.Score)}<br/><strong>q-Value:</strong> ${formatMetricValue(d['q-Value'], { normalDecimals: 6, sciDecimals: 2 })}<br/><strong>Impact:</strong> ${formatImpact(d.Impact)}<br/><strong>Coverage:</strong> ${formatCoverage(d.Coverage)}<br/><strong>Homogeneity:</strong> ${formatMetricValue(d.Homogeneity, { normalDecimals: 6, sciDecimals: 2 })}</div>`)
                .style("left", (event.pageX + 15) + "px")
                .style("top", (event.pageY - 28) + "px");
            d3.select(this).style("stroke", "black").style("stroke-width", 2);
        })
        .on("mouseout", function() {
            tooltip.transition().duration(500).style("opacity", 0);
            d3.select(this).style("stroke", "#fff").style("stroke-width", 0.5);
        });
        
    const zoomed = (event) => {
        const transform = event.transform;
        const newXScale = transform.rescaleX(xScale);
        const newYScale = transform.rescaleY(yScale);

        xAxisGroup.call(xAxis.scale(newXScale));
        yAxisGroup.call(yAxis.scale(newYScale));

        circlesGroup.selectAll("circle")
            .attr('cx', d => newXScale(d.tsneX))
            .attr('cy', d => newYScale(d.tsneY));
    };

    const zoom = d3.zoom()
        .scaleExtent([0.5, 10])
        .extent([[0, 0], [width, height]])
        .on("zoom", zoomed);
        
    svg.call(zoom);

    const legend = svg.append("g")
        .attr("class", "legend")
        .attr("transform", `translate(${width + 20}, 20)`);

    const colorLegend = legend.append("g").attr("class", "legend-color");
    const gradient = colorLegend.append("defs").append("linearGradient").attr("id", "gradient-color").attr("x1", "0%").attr("y1", "100%").attr("x2", "0%").attr("y2", "0%");
    gradient.selectAll("stop")
        .data(colorScale.ticks().map((t, i, n) => ({ offset: `${100*i/n.length}%`, color: colorScale(t) })))
        .enter().append("stop")
        .attr("offset", d => d.offset)
        .attr("stop-color", d => d.color);

    colorLegend.append("rect")
        .attr("width", 20)
        .attr("height", 120)
        .style("fill", "url(#gradient-color)");

    const colorAxis = d3.axisRight(d3.scaleLinear().domain(colorScale.domain()).range([120, 0])).ticks(5);
    colorLegend.append("g").attr("transform", "translate(20,0)").call(colorAxis);
    colorLegend.append("text").attr("x", 10).attr("y", -10).attr("fill", "#000").style("text-anchor", "middle").text("Score");

    const sizeLegend = legend.append("g").attr("class", "legend-size").attr("transform", "translate(0, 180)");
    const sizeData = [d3.min(validData, d => d.Coverage), d3.median(validData, d => d.Coverage), d3.max(validData, d => d.Coverage)];
    sizeLegend.selectAll("circle")
        .data(sizeData)
        .enter().append("circle")
        .attr("cy", (d, i) => i * 40)
        .attr("r", d => radiusScale(d))
        .style("fill", "gray");

    sizeLegend.selectAll("text")
        .data(sizeData)
        .enter().append("text")
        .attr("x", 30)
        .attr("y", (d, i) => i * 40)
        .attr("dy", "0.3em")
        .text(d => `${(d * 100).toFixed(1)}%`)
        .style("font-size", "12px");

    sizeLegend.append("text").attr("x", 10).attr("y", -20).attr("fill", "#000").style("text-anchor", "middle").text("Coverage");
}

function renderHeatmap(hypotheses) {
    const container = document.getElementById('hypotheses-heatmap-container');
    if (!container) {
        console.error("Hypotheses heatmap container element not found.");
        return;
    }
    container.innerHTML = '';

    const calculateCoOccurrence = (hypList) => {
        const allAttributes = new Set();
        hypList.forEach(hyp => {
            const attributes = extractAttributesFromHypothesis(hyp.Hypothesis_Text);
            attributes.forEach(attr => {
                allAttributes.add(`${attr.attribute} = '${attr.value}'`);
            });
        });
        const attributeLabels = Array.from(allAttributes);
        const attrMap = new Map(attributeLabels.map((attr, i) => [attr, i]));
        const matrixSize = attributeLabels.length;

        if (matrixSize < 2) return null;

        const coOccurrenceMatrix = Array(matrixSize).fill(0).map(() => Array(matrixSize).fill(0));

        hypList.forEach(hyp => {
            const attributesInHyp = extractAttributesFromHypothesis(hyp.Hypothesis_Text).map(attr => `${attr.attribute} = '${attr.value}'`);
            for (let i = 0; i < attributesInHyp.length; i++) {
                for (let j = i; j < attributesInHyp.length; j++) {
                    const attr1 = attributesInHyp[i];
                    const attr2 = attributesInHyp[j];
                    const idx1 = attrMap.get(attr1);
                    const idx2 = attrMap.get(attr2);
                    if (idx1 !== undefined && idx2 !== undefined) {
                        coOccurrenceMatrix[idx1][idx2]++;
                        if (idx1 !== idx2) {
                            coOccurrenceMatrix[idx2][idx1]++;
                        }
                    }
                }
            }
        });

        return { z: coOccurrenceMatrix, x: attributeLabels, y: attributeLabels };
    };

    const topHypotheses = [
        ...categorizedHypotheses['greater than'].slice(0, 10),
        ...categorizedHypotheses['less than'].slice(0, 10),
        ...categorizedHypotheses['variance is higher'].slice(0, 10)
    ];
    
    const topHeatmapData = calculateCoOccurrence(topHypotheses);
    const allHeatmapData = calculateCoOccurrence(hypotheses);

    container.innerHTML = `
        <div class="p-4 border rounded-lg bg-white flex flex-col items-center" style="height: 1600px; overflow: auto;">
            <h4 class="text-md font-semibold text-gray-800 mb-2">Co-occurrence in Top 30 Hypotheses</h4>
            <div id="plotly-heatmap-top-area"></div>
            <hr class="my-8 w-4/5">
            <h4 class="text-md font-semibold text-gray-800 mb-2">Co-occurrence in All Hypotheses</h4>
            <div id="plotly-heatmap-all-area"></div>
        </div>`;
        
    const plotAreaTop = document.getElementById('plotly-heatmap-top-area');
    const plotAreaAll = document.getElementById('plotly-heatmap-all-area');

    const layout = {
        width: 1200,
        height: 700,
        xaxis: { automargin: true },
        yaxis: { automargin: true },
        margin: { t: 50, l: 250, r: 50, b: 250 }
    };

    if (typeof Plotly !== 'undefined') {
        if (topHeatmapData) {
            Plotly.newPlot(plotAreaTop, [{
                ...topHeatmapData,
                type: 'heatmap',
                colorscale: 'Viridis',
                hoverongaps: false,
                hovertemplate: '<b>Attr 1</b>: %{y}<br><b>Attr 2</b>: %{x}<br><b>Co-occurrences</b>: %{z}<extra></extra>'
            }], { ...layout, title: 'Attribute Co-occurrence in Top 30 Hypotheses' });
        } else {
            plotAreaTop.innerHTML = `<div class="p-4 text-center text-gray-500">Not enough attribute diversity in top hypotheses to create a co-occurrence matrix.</div>`;
        }

        if (allHeatmapData) {
            Plotly.newPlot(plotAreaAll, [{
                ...allHeatmapData,
                type: 'heatmap',
                colorscale: 'Viridis',
                hoverongaps: false,
                hovertemplate: '<b>Attr 1</b>: %{y}<br><b>Attr 2</b>: %{x}<br><b>Co-occurrences</b>: %{z}<extra></extra>'
            }], { ...layout, title: 'Attribute Co-occurrence in All Hypotheses' });
        } else {
            plotAreaAll.innerHTML = `<div class="p-4 text-center text-gray-500">Not enough attribute diversity in all hypotheses to create a co-occurrence matrix.</div>`;
        }
    } else {
        console.error("Plotly.js library not found.");
        container.innerHTML = '<div class="error-message">Plotly.js library not found.</div>';
    }
}

function renderMetrics(hypotheses) {
    const container = document.getElementById('hypotheses-heatmap-metrics');
    if (!container) {
        console.error("Metric analysis container element not found.");
        return;
    }
    container.innerHTML = '';

    const validData = hypotheses.filter(h =>
        h.Impact_Lift != null && !isNaN(h.Impact_Lift) &&
        h.Coverage != null && !isNaN(h.Coverage) &&
        h.Fitness_Score != null && !isNaN(h.Fitness_Score) &&
        h.Significance_qValue != null && !isNaN(h.Significance_qValue)
    );

    if (validData.length === 0) {
        container.innerHTML = `<div class="p-4 text-center text-gray-500">No valid data available to render the metrics plot.</div>`;
        return;
    }
    
    const significanceSizes = validData.map(h => -Math.log10(Number(h.Significance_qValue || 1) + 1e-10) * 3);
    const minSize = Math.min(...significanceSizes);
    const maxSize = Math.max(...significanceSizes);
    const sortedSizes = [...significanceSizes].sort((a, b) => a - b);
    const medianSize = sortedSizes[Math.floor(sortedSizes.length / 2)];

    const plotData = {
        x: validData.map(h => h.Coverage),
        y: validData.map(h => h.Impact_Lift),
        text: validData.map(h => `<b>Hypothesis:</b> ${String(h.Hypothesis_Text || '').replace(/\*\*|`/g, '')}<br><b>Score:</b> ${formatScore(h.Fitness_Score)}<br><b>Impact:</b> ${formatImpact(h.Impact_Lift)}<br><b>Coverage:</b> ${formatCoverage(h.Coverage)}<br><b>q-Value:</b> ${formatQValue(h)}<br><b>Homogeneity:</b> ${formatHomogeneity(h)}`),
        mode: 'markers',
        type: 'scatter',
        hoverinfo: 'text',
        showlegend: false,
        marker: {
            color: validData.map(h => h.Fitness_Score),
            size: significanceSizes,
            colorscale: 'Viridis',
            showscale: true,
            colorbar: {
                title: 'Fitness Score',
                len: 0.5,
                y: 0.5,
                yanchor: 'middle',
                titleside: 'right',
                titlefont: { size: 10 },
                tickfont: { size: 8 }
            }
        }
    };
    
    const legendTraces = [
        {
            x: [null], y: [null], mode: 'markers', name: 'High Significance',
            marker: { size: maxSize, color: 'rgba(128, 128, 128, 0.7)' }
        },
        {
            x: [null], y: [null], mode: 'markers', name: 'Medium Significance',
            marker: { size: medianSize, color: 'rgba(128, 128, 128, 0.7)' }
        },
        {
            x: [null], y: [null], mode: 'markers', name: 'Low Significance',
            marker: { size: minSize, color: 'rgba(128, 128, 128, 0.7)' }
        }
    ];

    const layout = {
        title: 'Impact vs. Coverage of Hypotheses',
        xaxis: {
            title: 'Coverage',
            automargin: true
        },
        yaxis: {
            title: 'Impact (Lift)',
            automargin: true
        },
        hovermode: 'closest',
        width: 1200,
        height: 700,
        margin: { t: 50, l: 80, r: 180, b: 80 },
        showlegend: true,
        legend: {
            title: { text: 'Significance (Size)' },
            y: 1,
            yanchor: 'top'
        }
    };

    container.innerHTML = `<div class="p-4 border rounded-lg bg-white flex justify-center" style="overflow: auto;">
                               <div id="plotly-metrics-area"></div>
                           </div>`;
    const plotArea = document.getElementById('plotly-metrics-area');

    if (typeof Plotly !== 'undefined') {
        Plotly.newPlot(plotArea, [plotData, ...legendTraces], layout);
    } else {
        console.error("Plotly.js library not found.");
        container.innerHTML = '<div class="error-message">Plotly.js library not found.</div>';
    }
}